# Generated by Django 4.1.1 on 2023-02-11 05:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0002_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='development',
            name='request_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='internship',
            name='request_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
