# Generated by Django 4.1.1 on 2023-02-11 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0003_development_request_date_internship_request_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='development',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
