# Generated by Django 4.1.1 on 2023-02-11 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0004_alter_development_request_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='development',
            name='request_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='request_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
